/**
 * This file is needed because it is used by vscode and other tools that
 * call `jest` directly.  However, unless you are doing anything special
 * do not edit this file
 */
const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

/**
 * Exports
 */
module.exports = {
  ...standard.jestConfig(),
  setupFilesAfterEnv: ['<rootDir>/jest-setup.js'],
  collectCoverage: true,
};
