name: Daily E2E using Grafana Main

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup playwright browser
        run: npx playwright install --with-deps chromium

      - name: Start Grafana
        run: docker-compose -f test/docker-compose.yml up -d

      - name: Run e2e tests
        run: npm run e2e

      - name: Stop Grafana
        run: docker-compose down
