name: E2E Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sign plugin
        run: npm run sign
        env:
          GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}

      - name: Setup playwright browser
        run: npx playwright install --with-deps chromium

      - name: Start Grafana
        run: docker-compose -f test/docker-compose.yml up -d

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Stop Grafana
        run: docker-compose down
